### ISSUE TITLE
Porting your scipy extensions into autograd

### ISSUE THREAD

**Issue by duvenaud** [ebresch/gpExperiments#1]
I noticed you worked out the gradients w.r.t. the multivariate normal log-pdf:
https://github.com/ebresch/gpExperiments/blob/master/eriksExtensionsSCIPY.py#L28

Do you mind if we copy these into autograd? (With credit, of course!)

**Comment by ebresch** [comment]
Dear David,

First of all, thank you very much for developing Autograd, and for making
it available for everyone!

Yes, feel free to integrate the log-normal derivatives. They're from M.
Giles paper which you also reference in autograd/numpy/linalg.py.

I see you also wrote another message. Let me reply to that separately...

Best,
-Erik

**Comment by duvenaud** [comment]
Thanks!  I just updated autograd with multivariate normal derivatives.
They ended up being a little different than what you had, since numpy only
uses the lower half of the covariance matrix.
